title: Eve Research Foundation
description: Introducing Eve Research Foundation
sitename: Eve Research Foundation
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
